stages:
- test
- build
- deploy

services:
  - postgres:9.5
  - docker:dind

variables:
  POSTGRES_DB: testing_db
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

test app:
  stage: test
  image: python:3.8-slim-buster
  before_script:
  - pip install -r requirements.txt pytest-cov
  script:
  - pytest --cov=./
  after_script:
  - pip install codecov
  - codecov -t=$CODECOV_TOKEN

build_image:
  stage: build
  image: docker:latest
  services:
  - docker:dind
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker build -t registry.gitlab.com/evagelos/ac-rank .
  - docker push registry.gitlab.com/evagelos/ac-rank:latest
  only:
  - master
  - tags

deploy_image:
  stage: deploy
  before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  script:
  - ssh $SERVER "echo $CI_BUILD_TOKEN | ./deploy_ac_rank.sh" gitlab-ci-token
  after_script:
  - sleep 2
  - curl $WEBSITE_URL
  environment:
    name: production
    url: $WEBSITE_URL
  only:
  - master
  - tags


include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
