stages:
- build

build_image:
  stage: build
  image: docker:latest
  services:
  - docker:dind
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker build -t registry.gitlab.com/evagelos/ac_rank .
  - docker push registry.gitlab.com/evagelos/ac_rank:latest
  only:
  - master
