stages:
- test
- build
- deploy

services:
  - postgres:9.5
  - docker:dind

test app:
  stage: test
  image: python:3.5-alpine
  before_script:
  - python -m pip install -r requirements/development.txt
  script:
  - python -m pytest

build_image:
  stage: build
  image: docker:latest
  services:
  - docker:dind
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker build -t registry.gitlab.com/evagelos/ac-rank .
  - docker push registry.gitlab.com/evagelos/ac-rank:latest
  only:
  - master

deploy_image:
  stage: deploy
  before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
  - ssh $SERVER './deploy_ac_rank.sh' gitlab-ci-token $CI_BUILD_TOKEN
  environment:
    name: production
    url: $WEBSITE_URL
  only:
  - master
