# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 14:12
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('upgrade', models.CharField(blank=True, choices=[('s1', 'Step1'), ('s2', 'Step2'), ('s3', 'Step3'), ('drift', 'Drift'), ('dtm', 'Gr.A 92'), ('gra', 'Group A'), ('tuned', 'Tuned')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laptime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('splits', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptimes.Car')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sectors', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.AddField(
            model_name='laptime',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptimes.Track'),
        ),
        migrations.AddField(
            model_name='laptime',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
