# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 14:23
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('laptimes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('upgrade', models.CharField(blank=True, choices=[('s1', 'Step1'), ('s2', 'Step2'), ('s3', 'Step3'), ('drift', 'Drift'), ('dtm', 'Gr.A 92'), ('gra', 'Group A'), ('tuned', 'Tuned')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sectors', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.RemoveField(
            model_name='laptime',
            name='sector_times',
        ),
        migrations.AddField(
            model_name='laptime',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptime',
            name='splits',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=[3, 4, 5], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptime',
            name='car',
            field=models.OneToOneField(default='ferrari', on_delete=django.db.models.deletion.CASCADE, to='laptimes.Car'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptime',
            name='track',
            field=models.OneToOneField(default='monza', on_delete=django.db.models.deletion.CASCADE, to='laptimes.Track'),
            preserve_default=False,
        ),
    ]
