# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 08:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laptimes', '0002_auto_20170409_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptime',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptimes.Car'),
        ),
        migrations.AlterField(
            model_name='laptime',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptimes.Track'),
        ),
        migrations.AlterField(
            model_name='laptime',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
