# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptimes', '0002_auto_20170505_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='layout',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
