# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptimes', '0003_auto_20170507_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='circuit',
        ),
        migrations.AddField(
            model_name='track',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='upgrade',
            field=models.CharField(blank=True, choices=[('s1', 'Step1'), ('s2', 'Step2'), ('s3', 'Step3'), ('drift', 'Drift'), ('tuned', 'Tuned')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Circuit',
        ),
    ]
