# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptimes', '0005_auto_20170514_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='ac_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='upgrade',
            field=models.CharField(blank=True, choices=[('s1', 'Step 1'), ('s2', 'Step 2'), ('s3', 'Step 3'), ('drift', 'Drift'), ('tuned', 'Tuned')], max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=set([('ac_name', 'layout')]),
        ),
    ]
