# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptimes', '0006_auto_20180225_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='layout',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
