# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laptimes', '0008_auto_20180311_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_gear_2', models.SmallIntegerField(null=True)),
                ('internal_gear_3', models.SmallIntegerField(null=True)),
                ('internal_gear_4', models.SmallIntegerField(null=True)),
                ('internal_gear_5', models.SmallIntegerField(null=True)),
                ('internal_gear_6', models.SmallIntegerField(null=True)),
                ('internal_gear_7', models.SmallIntegerField(null=True)),
                ('final_ratio', models.SmallIntegerField(null=True)),
                ('tyres', models.SmallIntegerField(null=True)),
                ('pressure_lf', models.SmallIntegerField(null=True)),
                ('pressure_rf', models.SmallIntegerField(null=True)),
                ('pressure_lr', models.SmallIntegerField(null=True)),
                ('pressure_rr', models.SmallIntegerField(null=True)),
                ('fuel', models.SmallIntegerField(null=True)),
                ('arb_front', models.SmallIntegerField(null=True)),
                ('arb_rear', models.SmallIntegerField(null=True)),
                ('spring_rate_lf', models.SmallIntegerField(null=True)),
                ('rod_length_lf', models.SmallIntegerField(null=True)),
                ('spring_rate_rf', models.SmallIntegerField(null=True)),
                ('rod_length_rf', models.SmallIntegerField(null=True)),
                ('spring_rate_lr', models.SmallIntegerField(null=True)),
                ('rod_length_lr', models.SmallIntegerField(null=True)),
                ('spring_rate_rr', models.SmallIntegerField(null=True)),
                ('rod_length_rr', models.SmallIntegerField(null=True)),
                ('wing_1', models.SmallIntegerField(null=True)),
                ('wing_2', models.SmallIntegerField(null=True)),
                ('camber_lf', models.SmallIntegerField(null=True)),
                ('toe_out_lf', models.SmallIntegerField(null=True)),
                ('camber_rf', models.SmallIntegerField(null=True)),
                ('toe_out_rf', models.SmallIntegerField(null=True)),
                ('camber_lr', models.SmallIntegerField(null=True)),
                ('toe_out_lr', models.SmallIntegerField(null=True)),
                ('camber_rr', models.SmallIntegerField(null=True)),
                ('toe_out_rr', models.SmallIntegerField(null=True)),
                ('damp_fast_bump_lf', models.SmallIntegerField(null=True)),
                ('damp_bump_lf', models.SmallIntegerField(null=True)),
                ('damp_fast_rebound_lf', models.SmallIntegerField(null=True)),
                ('damp_rebound_lf', models.SmallIntegerField(null=True)),
                ('damp_fast_bump_rf', models.SmallIntegerField(null=True)),
                ('damp_bump_rf', models.SmallIntegerField(null=True)),
                ('damp_fast_rebound_rf', models.SmallIntegerField(null=True)),
                ('damp_rebound_rf', models.SmallIntegerField(null=True)),
                ('damp_fast_bump_lr', models.SmallIntegerField(null=True)),
                ('damp_bump_lr', models.SmallIntegerField(null=True)),
                ('damp_fast_rebound_lr', models.SmallIntegerField(null=True)),
                ('damp_rebound_lr', models.SmallIntegerField(null=True)),
                ('damp_fast_bump_rr', models.SmallIntegerField(null=True)),
                ('damp_bump_rr', models.SmallIntegerField(null=True)),
                ('damp_fast_rebound_rr', models.SmallIntegerField(null=True)),
                ('damp_rebound_rr', models.SmallIntegerField(null=True)),
                ('diff_power', models.SmallIntegerField(null=True)),
                ('diff_coast', models.SmallIntegerField(null=True)),
                ('front_bias', models.SmallIntegerField(null=True)),
                ('engine_limiter', models.SmallIntegerField(null=True)),
                ('bump_stop_rate_lf', models.SmallIntegerField(null=True)),
                ('packer_range_lf', models.SmallIntegerField(null=True)),
                ('bump_stop_rate_rf', models.SmallIntegerField(null=True)),
                ('packer_range_rf', models.SmallIntegerField(null=True)),
                ('bump_stop_rate_lr', models.SmallIntegerField(null=True)),
                ('packer_range_lr', models.SmallIntegerField(null=True)),
                ('bump_stop_rate_rr', models.SmallIntegerField(null=True)),
                ('packer_range_rr', models.SmallIntegerField(null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptimes.Car')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptimes.Track')),
            ],
        ),
        migrations.AddField(
            model_name='laptime',
            name='car_setup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laptimes.CarSetup'),
        ),
    ]
