# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laptimes', '0009_auto_20180321_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsetup',
            name='abs',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='carsetup',
            name='brake_power_mult',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='carsetup',
            name='traction_control',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='laptime',
            name='car_setup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laptimes.CarSetup'),
        ),
    ]
