# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laptimes', '0011_auto_20180407_1006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarSetup',
            new_name='Setup',
        ),
    ]
