# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptimes', '0012_auto_20180407_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='arb_front',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='arb_rear',
            field=models.IntegerField(null=True),
        ),
    ]
